### PR TITLE
convertStyleToAttrs: fix wrong character class

### PR DESCRIPTION
**Pull request by XhmikosR**
Was flagged by [lgtm](https://lgtm.com/projects/g/svg/svgo?mode=list)

### CODE REVIEW

**Comment by TrySound** [comment]
Would be good to cover it with test case

**Comment by TrySound** [comment]
Or nevermind. Eslint may cover it too.

**Comment by XhmikosR** [comment]
I'd add CodeQL or LGTM itself; unsure if ESLint detects it yet.

BTW I was planning to make a PR to add xo for linting. Do you have any preference regarding indentation etc?

**Comment by TrySound** [comment]
I'll add eslint myself. Prefer it to it to not force formatting. Will add prettier after dealing with pull requests.

**Comment by XhmikosR** [comment]
@TrySound could you please finish with the remaining styli/linting tweaks? I'd like to take a closer look at some things and right now things are inconsistent.

**Pull request merged**
