### PR TITLE
Improve css-class-list

### PR DESCRIPTION
**Pull request by XhmikosR**
* use `const`
* use spread
* use `for...of`
* remove two internal functions only called once

### CODE REVIEW

**Comment by TrySound** [comment]
This code will be killed in v3. No need to touch it at all.

**Comment by XhmikosR** [comment]
Is that documented somewhere? I wasn't aware of that, nor do I know when v3 will be out.

**Comment by TrySound** [comment]
Whole JSAPI class is gonna be removed. SVGO plugins will work with plain object ast.

**Comment by XhmikosR** [comment]
Regardless, your call. If v3 is close, feel free to close this.

**Pull request closed without merging**
