### PR TITLE
Fix #820

### LINKED ISSUE #820: v1.0.0 regression: "TypeError: Object.defineProperty called on non-object" on certain SVGs
Take this SVG for example:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100">
  <foreignObject width="100%" height="100%">
    <style>div { color: red; }</style>
    <body xmlns="http://www.w3.org/1999/xhtml"><div>hello, world</div></body>
  </foreignObject>
</svg>
```

This looks like valid SVG to my eyes; it displays fine, and svgo v0.7.2 handles it just fine. However, with svgo v1.0.0:

```console
$ svgo sample.svg
TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at CSSStyleDeclaration.addStyleHandler (/usr/local/lib/node_modules/svgo/lib/svgo/css-style-declaration.js:36:12)
    at CSSStyleDeclaration.hasStyle (/usr/local/lib/node_modules/svgo/lib/svgo/css-style-declaration.js:26:10)
    at CSSStyleDeclaration.setProperty (/usr/local/lib/node_modules/svgo/lib/svgo/css-style-declaration.js:242:10)
    at Object.fn (/usr/local/lib/node_modules/svgo/plugins/inlineStyles.js:156:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/svgo/node_modules/css-tree/lib/walker/create.js:133:26)
    at List.each (/usr/local/lib/node_modules/svgo/node_modules/css-tree/lib/utils/list.js:143:12)
    at Object.walkDeclarations (/usr/local/lib/node_modules/svgo/node_modules/css-tree/lib/walker/create.js:131:27)
    at Object.walkDeclarations (/usr/local/lib/node_modules/svgo/node_modules/css-tree/lib/walker/create.js:124:34)
    at Object.walkDeclarations (/usr/local/lib/node_modules/svgo/node_modules/css-tree/lib/walker/create.js:285:30)
```

### PR DESCRIPTION
**Pull request by strarsis**
Fixes issue https://github.com/svg/svgo/issues/820.

### CODE REVIEW

**Comment by strarsis** [comment]
@GreLI, @zmwangx: Fixed, ready to merge.

**Comment by zmwangx** [comment]
I can verify that this fix works on all similar SVG files (that is, similar to the minimal failing case) that I have at hand.

**Comment by zmwangx** [comment]
@GreLI Any chance of a patch release?

**Comment by GreLI** [comment]
Released in v1.0.1.

**Comment by zmwangx** [comment]
Thanks!

**Pull request merged**
