### PR TITLE
adds addAttributes plugin

### PR DESCRIPTION
**Pull request by gjjones**
Allows adding valueless attributes to the svg element.

### CODE REVIEW

**Comment by gjjones** [comment]
This PR is meant to address #543

**Comment by mattyod** [comment]
+1

**Comment by UsulPro** [comment]
Hi!
Am I right that it convert svg code to one jsx-sutable ?
if it so could you, please, give a short example how to use it finally?

**Comment by gjjones** [comment]
@UsulPro, here is an example of how I used it for a plugin to convert SVGs to React components:
https://gitlab.com/gjjones/svg-to-react/blob/master/src/utilities.js#L6

**Pull request merged**
