### PR TITLE
Add p-try to fix tests

### PR DESCRIPTION
**Pull request by lamartire**
Now it's not possible to run tests locally, because project is missing `p-try` module.

### CODE REVIEW

**Comment by lamartire** [comment]
@TrySound can you take a look, please?

**Comment by TrySound** [comment]
Everything works without p-try. Not sure what's the problem you see.

**Comment by lamartire** [comment]
In the latest `master` I have:
image

**Comment by TrySound** [comment]
Try to use npm 6

**Comment by lamartire** [comment]
Problem was reproduced with `npm@7`. `npm@6` doesn't work either:

image

**Comment by TrySound** [comment]
Try `npm ci`

**Comment by lamartire** [comment]
I think, it should be possible to run tests with any `npm` locally.

**Comment by TrySound** [comment]
I'm trying to figure out the problem. `npm ci` command does not updates dependencies implicitly.

**Comment by lamartire** [comment]
Can't do that locally. Can you have an idea, what can be wrong?

image

**Comment by TrySound** [comment]
A have a feeling npm is bullshitting us

**Comment by lamartire** [comment]
> A have a feeling npm is bullshitting us

Very likely! 😅

**Comment by TrySound** [comment]
Migrated to jest. Though I think the problem in package manager or maybe fs.

**Comment by lamartire** [comment]
Ok, nice!

**Pull request closed without merging**
