### PR TITLE
Allow element separator to be changed in config

### LINKED ISSUE #557: Remove xmlns:xlink
How do I remove: `xmlns:xlink="http://www.w3.org/1999/xlink"` from the SVG?

As using: `{removeAttrs: { attrs: ['svg:xmlns', 'svg:xmlns:xlink'] }},` doesn't work... only the `xmlns` is removed.

### PR DESCRIPTION
**Pull request by mikestreety**
This resolves #557 as you can pass in a different character for element seperation (e.g. `^`

### CODE REVIEW

**Comment by GreLI** [comment]
Linter fails because the param name is not in camel case. Also, it's not the best name for the param.

**Comment by mikestreety** [comment]
Ah appologies @GreLI - I just took the existing variable and dropped it in.

Suggestions on param name?

**Comment by GreLI** [comment]
Ideally, I'd change syntax to something like `'path[fill]'` with taking attribute name in brackets like in CSS.

**Comment by mikestreety** [comment]
Yeah, that would be great. Unfortunately that's beyond me :( I could correct the camel case then raise an issue for this to be an "upgrade"?

**Comment by GreLI** [comment]
That's not a great improvement, probably, I'll do it myself before releasing new version.

**Comment by mikestreety** [comment]
Ok thanks. 

To add a bit of context, Figma drops `figma:type="canvas"` and `xmlns:figma="http://www.figma.com/figma/ns"` attributes all over the SVG with invalidates it for anything but figma!

**Comment by GreLI** [comment]
Adopted and merged in 645908923bb163e177023ca21fe04a380fade126.

**Pull request closed without merging**
