### PR TITLE
After ‘arcto’ path command(a or A), spaces are no longer removed by default

### PR DESCRIPTION
**Pull request by yisibl**
## Background

In the [svg elliptical arc curve commands](https://www.w3.org/TR/SVG11/paths.html#PathDataEllipticalArcCommands), the white space after `large-arc-flag` and `sweep-flag` can be removed. Svgo was implemented here(https://github.com/svg/svgo/commit/258fecfa6b4a037d98ad2614f5c9573728f6959d) before and enabled by default. 

[The idea of the implementer](https://github.com/svg/svgo/issues/1137#issuecomment-518351171) @GreLI  at the time was:

> It's a totally standard syntax from a 8-years old specification (and was introduced in a working draft a year before). If some software has a problems with it—those should be addressed to that software.

However, [more and more people report that there will be problems](https://github.com/svg/svgo/issues/1137 ). I think that as an svg compressor, security and compatibility are the most important. Although browsers all support omitting the white space after large-arc-flag and sweep-flag, mainstream vector software such as Sketch and Adobe Illustrator do not support it. Even if these software are supported, they are paid software, and the upgrade cost for users is huge. As a designer, I can't understand why the SVG file compressed by svgo will make an error when reopened. We can't think about the problem from the perspective of a developer who can write code. Even for a developer, the rules of path data are obscure.

image

So this PR disables the `noSpaceAfterFlags` option by default. Although the compressed file size increases slightly, I think it is worth it. If your SVG file is only used in the browser or pursues the ultimate file size, you can enable it through the following options:

```json
{
    "plugins": [
        { "convertPathData": { "noSpaceAfterFlags": true } },
        { "mergePaths": { "noSpaceAfterFlags": true } }
    ]
}
```

Fixed:  https://github.com/svg/svgo/issues/1317 https://github.com/svg/svgo/issues/1138  https://github.com/svg/svgo/issues/1164 https://github.com/svg/svgo/issues/1183 https://github.com/svg/svgo/issues/1189

### CODE REVIEW

**Comment by yisibl** [comment]
@TrySound PTAL

**Comment by TrySound** [comment]
Thanks a lot @yisibl!

**Comment by Jupi007** [comment]
Thanks @yisibl 👍

**Comment by yisibl** [comment]
Can you help me change the git email and username of the master branch commit? I used the wrong company mailbox. Or I resubmit a PR. Thanks a lot.

**Comment by TrySound** [comment]
Sorry, don't want to rewrite master history especially after release. Looks like both are here. Is it a big problem?
image

**Comment by yisibl** [comment]
You are so fast! That's it for now.

**Comment by GreLI** [comment]
It's a fame, that software doesn't support  SVG well 😒

**Pull request merged**
