### PR TITLE
Updated colorNames according to CSS Color Module Level 4

### PR DESCRIPTION
**Pull request by ydaniv**
Mostly missing variants of gray/grey and added rebeccapurple.

### CODE REVIEW

**Comment by ydaniv** [comment]
Should note that currently `colorsNames` contain values in short hex format, which currently goes against current API description and docs, which state that it will translate color names to long hex.

I'd gladly add a commit that fixes all of these to long format if there's no objection.

**Comment by Yeti-or** [comment]
convertColors plugin choose what is shorter `rgb()` `hex` or `name`. So I think that docs are correct right now

**Comment by ydaniv** [comment]
@Yeti-or yes, took me awhile to figure out the purpose of all the different collections (:
but the problem is that if you set the config to:
```
shorthex: false
shortname: false
```
You'll expect all hexes to be in long format, but they won't.

And besides, there are some valid color names from the specs that are missing.

**Comment by ydaniv** [comment]
:+1:

**Pull request merged**
