### PR TITLE
Convert ellipses circles

### PR DESCRIPTION
**Pull request by alexjlockwood**
The ability to convert circles and ellipses to paths has been requested a few times, for example in #652.

This pull request adds the ability to do just that.

LMK what you think!

### CODE REVIEW

**Comment by strarsis** [comment]
Is this similar to this PR?: https://github.com/svg/svgo/pull/652

**Comment by alexjlockwood** [comment]
@strarsis Yeah, except instead of creating a new plugin it adds the functionality to the existing plugin.

**Comment by alexjlockwood** [comment]
Also, sorry... the tests are failing because of jshint errors (I ported it from a personal project I wrote in es6 and forgot to fix the hoisting stuff :P). Easy to fix... but I'll wait to hear back on whether or not you want me to continue following through on this.

**Comment by drewnoakes** [comment]
Is there anything blocking this PR other than the jshint errors? I would be happy to address those if it'll get a PR merged. Can add unit tests too.

**Comment by GreLI** [comment]
Well, in general `<path>`'ll be longer then `<circle>` and `<ellipse>`—that's why I didn't it initially. So, there should be an option, I think. Like `convertCircles`, disabled by default.

**Comment by drewnoakes** [comment]
Here's a concrete example of the increase in size, assuming integral parameters:

```xml
<circle cx="100" cy="100" r="50"/>

<path d="M100 50a50 50 0 1 0 0 100 50 50 0 1 0 0-100z"/>
```

There _might_ be cases where converting circles to paths allows further path merging to occur, resulting in a net gain. I haven't seen any mention of optimisation heuristics/backtracking though.

So adding a default-disabled option seems harmless, but I'm not sure whether it'd ever make sense to turn it on.

**Comment by GreLI** [comment]
Yes it might, but that is not certain.

**Comment by geekbleek** [comment]
I have a number of use cases for converting circles and ellipses - ultimately because I'm not trying to optimize file size - I'm trying to optimize compatibility of all my SVG files.  If I can help with this PR please let me know!

**Comment by GreLI** [comment]
Few issues are here:

- it should be optional
- there're errors in code, it doesn't work
- lack of test.

**Comment by strarsis** [comment]
@alexjlockwood: There are jshint errors which prevent the tests to pass: 
https://travis-ci.org/svg/svgo/jobs/219732094#L246

**Comment by alexjlockwood** [comment]
Sorry about that, will try to fix that up now. :)

**Comment by alexjlockwood** [comment]
Blah... looks like I accidentally deleted my svgo fork. Is it possible to update the pull request if I've done that? Or will I have to create a new one...

**Comment by GreLI** [comment]
No idea, I'm afraid you have to make a new PR.

**Comment by alexjlockwood** [comment]
Going to close this and continue the work here: #818

**Pull request closed without merging**
