### PR TITLE
Change indent level to 2

### LINKED ISSUE #424: Change the indentation to 2 instead of 4 for the --pretty.
So it could be pretty and a bit smaller :) 2 is the new 4 anyway :dancer:

### PR DESCRIPTION
**Pull request by lipis**
Fixes #424 (almost 6K saved from the tests :dancer:)

### CODE REVIEW

**Comment by lipis** [comment]
Not sure how to resolve this test: https://travis-ci.org/svg/svgo/jobs/93412457

**Comment by GreLI** [comment]
I think it should be an option, not the hardcoded change.

**Comment by lipis** [comment]
I thought about it as an option.. but then again it doesn't make much sense :) It's still pretty and smaller.. Let's sleep on and see tomorrow.. :night_with_stars:

**Comment by levibuzolic** [comment]
Would love to see this as an option. I'd love for 2 spaces, though I'm sure there's people who prefer actual tab characters or 4 spaces. :ok_hand:

**Comment by lipis** [comment]
I'm not sure how to add it as an option (not much time for it), but my opinion is that there is no much need for it to add the extra complexity.. having said that if anyone want's to contribute.. please do so! I just want to be able to use the 2 spaces :)

**Comment by lipis** [comment]
If we are about to merge this one though... let me know how can I fix the last test..

**Comment by febLey** [comment]
I'd also love the change the indent level to 2

**Comment by lipis** [comment]
shall we merge that one?

**Comment by GreLI** [comment]
See https://github.com/svg/svgo/pull/465#issuecomment-159978721:
> I think it should be an option, not the hardcoded change.

**Comment by lipis** [comment]
Can someone implement this then if anyone with spare time?

**Comment by scurker** [comment]
With #526, I added the ability to pretty print svgs with an optional indent level. There really wasn't an existing (good) place to write the test for this, but I wanted to at least implement something.

**Comment by GreLI** [comment]
Closed in favor of #526.

**Comment by GreLI** [comment]
[v0.6.4](https://github.com/svg/svgo/releases/tag/v0.6.4) with `--indent` option has been just released.

**Comment by lipis** [comment]
:+1:

**Pull request closed without merging**
