### PR TITLE
Convert circles/ellipses to paths

### PR DESCRIPTION
**Pull request by alexjlockwood**
The ability to convert circles and ellipses to paths has been requested a few times, for example in #652.

This pull request adds the ability to do just that.

LMK what you think!

See #702 for earlier work on this.

### CODE REVIEW

**Comment by GreLI** [comment]
Issues from the original one are still present here:

- it should be optional
- there're errors in code, it doesn't work
- lack of tests.

**Comment by alexjlockwood** [comment]
Fixed the errors, will add some tests later tonight!

@GreLi how do you suggest I make this optional?

**Comment by GreLI** [comment]
Just an option for the plugin like `convertEllipses`.

**Comment by alexjlockwood** [comment]
Would you prefer two options (one for circles and a second for ellipses)?

**Comment by GreLI** [comment]
I think one is enough, may be shorten to like `convertArcs`, but if you see such a point, you're welcome.

**Comment by alexjlockwood** [comment]
Cool, sounds good. I'll add some tests tonight when I get back from work.

**Comment by alexjlockwood** [comment]
@GreLI I added a simple test case and fixed up the code. LMK what you think!

**Comment by GreLI** [comment]
:

**Comment by GreLI** [comment]
SVGO v1.0.0 with this change has been released now.

**Comment by buisine** [comment]
@alexjlockwood 

Hi looklike ellipse element are not converted to paths

made test on commande line like : 

➜  svg svgo --enable=convertShapeToPath 1.svg

➜  svg svgo --enable=convertShapeToPath --config=conf.json --pretty 1.svg 

with config.json having { "convertArcs": true }

Can you help please ?

**Comment by alexjlockwood** [comment]
@buisine I recommend filing a bug with the SVG you are trying to convert and the svgo version you are using.

**Comment by buisine** [comment]
@alexjlockwood 
Thanks.

For now i edited plugin source : 
    exports.params = { convertArcs: true }; 

in convertShapeToPath.js
and it does the job !
thought my config is bad.

**Pull request merged**
