### PR TITLE
Sort plugin lists alphabetically

### PR DESCRIPTION
**Pull request by yialo**
To simplify search of particular plugin description at page.

### CODE REVIEW

**Comment by TrySound** [comment]
See https://github.com/svg/svgo/pull/1430

**Comment by yialo** [comment]
Is it crucial to follow this order in `plugins` array in config file?

**Comment by TrySound** [comment]
Yep. Currently some plugins cannot work in isolation and requires others. I'm working on decoupling though.

**Comment by polarathene** [comment]
Regarding copy/paste concern, how does that apply to the built-in plugins table? I've often found that a bit annoying to scan through. If the concern is that someone may copy/paste and edit it to add non-default plugins, then it's better to add a note before the table that order of appearance is important, then provide a copy/paste list for that which if you don't want to add too much noise to the README can link to another markdown document (or JS config), or hide the content in an expandable `<details>` block.

**Comment by TrySound** [comment]
Table is fine to reorder

**Pull request closed without merging**
