### PR TITLE
add mergeText plugin

### LINKED ISSUE #964: Improvement merge text and tspan
I would like to merge simple `<text>` with `<tspan>`

Inputexample:
```svg
 <text x="313.88" y="322.89">
  <tspan x="313.88" y="322.89">1</tspan>
 </text>
```
Output:
```svg
 <text x="313.88" y="322.89">1</text>
```

It does not have to work for everything, but I just want that it works in "simple" cases.

I already for this improvement somewhere else: https://github.com/RazrFalcon/svgcleaner/issues/127 and https://github.com/scour-project/scour/issues/201

### LINKED ISSUE #1907: mergeText plugin to consolidate text/tspan elements
The Inkscape text tool creates verbose and redundant elements, with a `<tspan>` inside a `<text>` element. These can often be consolidated, by merging adjacent `<text>` elements, resulting in a single `<text>` element containing multiple `<tspan>` elements.

For example:
``` 
   <text x="45.869" y="38.606">
        <tspan x="45.869" y="38.606">Part one</tspan>
    </text>
    <text x="87.151" y="89.826">
        <tspan x="87.151" y="89.826">Part two</tspan>
    </text>
``` 
becomes
``` 
   <text>
        <tspan x="45.869" y="38.606">Part one</tspan>
        <tspan x="87.151" y="89.826">Part two</tspan>
    </text>
``` 
A `<text>` element containing a single `<tspan>` can also be consolidated - see issue #964

### PR DESCRIPTION
**Pull request by johnkenny54**
Consolidate adjacent `<text>` elements and `<text>` elements with a single `<tspan>` child.

Resolves #964, resolves #1907

### CODE REVIEW

**Comment by johnkenny54** [comment]
There are problems with the commits in my branch. Closing this PR, will reopen with a clean copy.

**Comment by SethFalco** [comment]
Thanks for opening and maintaining the pull request!

When you do have it open, I'll review it once SVGO v3.2.0 is released. Meanwhile, it will probably help if you update with a rebase instead of merge next time!

Assuming `origin` is your fork and `upstream` is this repository.

```sh
git fetch --all
git rebase upstream/main
```

Then if there are any conflicts, you can resolve them and do:

```sh
git add .
git rebase --continue
```

This results in a clean commit history, no merges required. 👍🏽
If you ever have trouble because of too many conflicts, it's simpler to squash your commits first and then rebase with upstream after.

```sh
git rebase -i HEAD~N # replace N with the number of commits you want to squash
# an interactive editor appears, replace "pick" in all lines except the first with "s"

// now rebase with upstream as normal
git fetch --all
git rebase upstream/main
```

**Comment by KTibow** [comment]
Thing is that usually merges work fine and don't include upstream commits in the change view, but I think somewhere commit history got changed, resulting in discontinuity across past upstream and current upstream. I ran into this when rebasing another PR I made, and fixed it by `git reset --hard HEAD~1`ing before retrying the merge.

**Comment by SethFalco** [comment]
Interesting, I always use rebase, so I haven't run into that issue.

> commit history got changed

In the past, some maintainers have done force pushes to `main`, however, that forcefully closes all pull requests that target it. That shouldn't be the problem.

I'm guessing it's because we use the "Squash and merge" strategy to merge pull requests.

> Because this commit is only on the base branch and not the head branch, the common ancestor of the two branches remains unchanged. If you continue to work on the head branch, then create a new pull request between the two branches, the pull request will include all of the commits since the common ancestor, including commits that you squashed and merged in the previous pull request.
> 
> — https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits

**Pull request closed without merging**
