### PR TITLE
In-code comments shorten the configuration section.

### PR DESCRIPTION
**Pull request by hugolpz**
Minor stylistic improvement for concise manual. See [side by side](https://github.com/svg/svgo/pull/1619/files).
- [x] Merge code examples in a single and better chosen example
- [x] Add inline comments to explain each section
- [x] Avoid verbose explanations and duplication.
- [x] All information kept.
- [x] Shorter and clearer.

### CODE REVIEW

**Comment by hugolpz** [comment]
@TrySound : this one is pretty easy to approve.

**Comment by hugolpz** [comment]
@omgovich, @matheus1lva and @renatorib : this readme.md improvement is pretty easy to approve.
 
 Also, please invide mode people to manage this repository, especially its PR. Project is lively, it requires more owners to manage those PR.

**Comment by TrySound** [comment]
Hi, sorry for waiting. I traveled and didn't have much time for open source.
Sadly can't review with removed fork. Will pick changes manually.

**Comment by TrySound** [comment]
Thanks for your help
https://github.com/svg/svgo/commit/8ae65b72821ea1b02660a460fd977fd64f53db6d

**Comment by hugolpz** [comment]
Seems you found a way. I cleaned up my repository list few days ago and may have removed my svgo forks, sorry if that made your PR less easy. Thanks for finding a workaround anyway 🍻

**Pull request closed without merging**
