### PR TITLE
Add currentColor plugin

### PR DESCRIPTION
**Pull request by epszaw**
Hello! 
I'm always working with monochrome icons, but in some cases I have really a lot of icons and want to change their `stroke` and `fill` from css. For that, I need to replace all values with `currentColor`  value. This do it pretty simple and fast. Except case - when attribute has value `none`, plugin will skip this attribute.

### CODE REVIEW

**Comment by lamartire** [comment]
@GreLI is here any activity? The last release was in October of 2019th. The most of pull requests is awaiting a lot of time.

**Comment by sayjeyhi** [comment]
I need this plugin too..

**Comment by lamartire** [comment]
@sayjeyhi it seems, that project is dead. I think, it is possible to make a fork and allow to users pass custom plugins.

**Comment by lamartire** [comment]
@TrySound as I understood, in `svgo@2` is coming? Should I update this PR and plugin?

**Comment by TrySound** [comment]
Sure. Though I will hold adding new plugins for now and will try to fix existing issues first.

**Comment by lamartire** [comment]
Ok, then I won't hurry with updating :D

**Comment by lamartire** [comment]
@TrySound all done :)
Also, I added `p-try` for correct unit-tests running, but also opened separated PR for that. I think, it doesn't matter if we merge this one first.

**Comment by lansolo99** [comment]
@lamartire  Hi, I used a forked version of your plugin, waiting for the PR to be merged, any update regarding this ? I find it would be more than a nice addition to official Svgo plugins 👍

**Comment by lamartire** [comment]
@TrySound I've just actualize here up to latest `master`

**Comment by SethFalco** [comment]
This was already a feature in SVGO via the `convertColor` plugin.
This config achieves what you want:

**`svgo.config.js`**
```js
module.exports = {
  plugins: [
    {
      name: "convertColors",
      params: {
        currentColor: true
      }
    }
  ]
}
```

Reference:
* https://github.com/svg/svgo/pull/521

**Pull request closed without merging**
