### PR TITLE
css-select library upgrade from v4.1.3 to v5.1.0

### PR DESCRIPTION
**Pull request by Annniee1**
Please Have a look at this .

### CODE REVIEW

**Comment by Annniee1** [comment]
@rlivsey @chromakode @devongovett @sonnyp Please Review this Pull Request

**Comment by Annniee1** [comment]
Hi @rlivsey @chromakode @devongovett @sonnyp any plan to merge this pr ?

**Comment by Annniee1** [comment]
Hi @TrySound @matheus1lva , Could you please review this PR once? Thanks!

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v3.0.0

**Pull request closed without merging**
