### PR TITLE
Add setDimensions plugin

### PR DESCRIPTION
**Pull request by allypalanzi**
Adds a setDimensions plugin that allows users to specify a width and height for their svg.

### CODE REVIEW

**Comment by GreLI** [comment]
Since the plugin needs only an outer `<svg>` it's better not to run it against every element, but use `var svg = data.content[0]` with `exports.type = 'full'` like it's done in [plugins/addClassesToSVGElement.js](/svg/svgo/blob/master/plugins/addClassesToSVGElement.js) (XML-prolog and doctype should be normally removed by corresponding plugins executed before).

Also, the value “50” of `width` and `height` seems to be too arbitrarily. It's better to set to common icon size like 16×16.

**Comment by allypalanzi** [comment]
Good point! I'll make that update. 50 was totally arbitrary – the idea was that it could be configured.

**Comment by htahmasebpour** [comment]
http://track.mlsend3.com/link/c/YT0yNjcyNjExMTg4NzgwNTg0MTImYz10Mmc1JmU9MTkyOCZiPTI4MzI5NzQ3JmQ9YjVwNmg2aw==.V8aWHpHHP7PwRNRaECVMwtfn-LawxA5x2n_D2scVVK8

**Comment by GreLI** [comment]
The plugin is trivial, so I'm closing it until a more elaborated version will come.

**Pull request closed without merging**
