### PR TITLE
Update badges in README.md

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
Add NPM and Discord logos. Label Discord badge as "Discord". Set Discord badge Color to 5865F2, Discord's official "Blurple" color.

### CODE REVIEW

**Comment by GreLI** [comment]
Who maintains brew svgo package and how it works? Does it need node.js?

**Comment by MichaelHinrichs** [comment]
Here.
https://formulae.brew.sh/formula/svgo#default

This says it needs node 22.3.0.

**Comment by GreLI** [comment]
Hmm, seems like the bottle is there for 7 years. Seems like updated automatically, probably from the github release.

**Comment by SethFalco** [comment]
I'm not seeing the benefit to this. It just adds bloat to the README with information no one is asking for, and most of it is readily available at the links we do have.

UX extends to project documentation and the README too, and imo this offers a worse experience for people learning about the project. For example, scattering around icons and colors everywhere with meaningless stats doesn't help anyone. It's just distracting from more important information we actually do want to convey to the user.

**Pull request closed without merging**
