### PR TITLE
Add minifyImages plugin to optimize embedded png and jpeg

### PR DESCRIPTION
**Pull request by julienboulay**
This new plugin allows to optimize png and jpeg with pngquant and jpegtran.
It fixes an existing issue : https://github.com/svg/svgo/issues/971

### CODE REVIEW

**Comment by canercandan** [comment]
@julienboulay what is the current state of this PR?

**Comment by julienboulay** [comment]
Hi @canercandan,
This PR has been rejected because it includes external non-js dependencies (pngquant and jpegtran)
See comments on issue #971

**Comment by GreLI** [comment]
For the report, execa requires Node >= 6, while SVGO currently runs on 4 and higher. Should bump it, but not yet :man_shrugging:. Also, need to do something with tests and CI. Maybe run them only locally.

**Comment by TrySound** [comment]
This PR adds a lot of packages. Though we would like to keep svgo as small as possible. You can publish this plugin as separate package. Configuration allows custom plugins.

**Pull request closed without merging**
