### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by TrySound**
No breaking changes. Fix my big dependency tree where js-yaml isn't small one.

### CODE REVIEW

**Comment by GreLI** [comment]
Yeah, I've seen it. Usually, I update dependencies when releasing a new version.

**Comment by GreLI** [comment]
Dependencies have been updated in [v0.6.0](https://github.com/svg/svgo/releases/tag/v0.6.0).

**Comment by TrySound** [comment]
@GreLI Thanks!

**Pull request closed without merging**
