### PR TITLE
Added option "dontUseDefaults"

### PR DESCRIPTION
**Pull request by Kreozot**
Added option "dontUseDefaults" which allows to not load default configuration.
It is usefull if you want to control what's going on with your SVG and don't want to list all available packages in your config.

### CODE REVIEW

**Comment by GreLI** [comment]
How it differs from `full: true` in config?

**Comment by Kreozot** [comment]
I'm glad you asked. Because first i was thinking that "full" flag is what i wanted. But with it "floatPrecision" parameter doesn't work. And also it is not documentated (so I don't figured out what is this for).
If you say that "full" flag is for ignoring the default config, so it still needs some code and documentation changes.

**Comment by Kreozot** [comment]
So, @GreLI, what's your decision?

**Comment by GreLI** [comment]
I believe, problems must be solved, not workarounded.

**Comment by Kreozot** [comment]
Can I speak with you on russian? Because i don't follow you.
Twitter/mail? What do you prefer?

**Comment by Kreozot** [comment]
Hello!  @GreLI! Anybody!

**Comment by GreLI** [comment]
Haven't looked into the problem yet.

**Comment by GreLI** [comment]
[v0.6.0](https://github.com/svg/svgo/releases/tag/v0.6.0) with the fix have been just released.

**Comment by Kreozot** [comment]
:+1: Thanks

**Pull request closed without merging**
