### PR TITLE
Fix compatibility issue with node v0.10.29

### PR DESCRIPTION
**Pull request by cravesoft**
for...of was first defined in ECMAScript 2015. This pull request replaces calls to for...of with calls to Map.prototype.forEach().

### CODE REVIEW

**Comment by GreLI** [comment]
The main reason of bumping dependencies to 0.12 is Map/Set, which are also not supported in 0.10. And I don't want to add polyfills useless for almost all.

**Comment by cravesoft** [comment]
OK, thanks for your answer. We now ask our users to install the latest nodejs from the nodesource binary repository.

**Comment by GreLI** [comment]
It's been reverted (but I managed keep the fix the original issue) in 8abdef7742e67d45ed39f677f8e808062563eb25.

**Comment by cravesoft** [comment]
Thank you very much for keeping me informed. It does indeed work with node v0.10.29 now.

**Pull request closed without merging**
