### PR TITLE
Remove the executable flag from files.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by TrySound** [comment]
I don't get. What this is about?

**Comment by XhmikosR** [comment]
These are wrongfully marked as executable files in git. There's no reason for them to be executable AFAICT.

**Comment by TrySound** [comment]
How did you detect and edit them?

**Comment by XhmikosR** [comment]
Well, I saw the files being marked as modified when I edit the repo through Windows on WSL, but you can run this to check:

```
\\wsl$\Ubuntu\home\xmr\repos\svgo>git ls-files -s . | findstr 100755
100755 0c2945204b74d462e5b5ddb31f32d1fa8655fdea 0       bin/svgo
100755 42d8eb20a69bc4ff95e797a02be4064e384a1355 0       lib/svgo.js
100755 de69ac891b42a4b1bdb8ed8e10eccea2b7fb10ec 0       logo/isotype-white.svg
100755 fda127ed1f58b2534a30286453d59bae102d0ef9 0       logo/isotype.svg
100755 a7df137e401020bcc32beb015584f4cb95f8b9e1 0       logo/logo-web.svg
100755 81a63f876b3c41dc719918fb1021295ed6a96e5f 0       logo/logo-white.svg
100755 1385c26565fd2be52aba007f66c50a41fcb73156 0       logo/logo.svg
100755 5cb822c3b00a2e0eab11d43e3b72d0abce40f925 0       plugins/minifyStyles.js
100755 d8a989b51ca3fa58857fd6f4c20da8a4ffd6b533 0       plugins/prefixIds.js
100755 9e8b029d2fc24e0a5b96d49c2c800ec921594698 0       test/plugins/minifyStyles.01.svg
100755 7b4a1ceaf9f97d91bcd54b1a59a990ba667edc28 0       test/plugins/minifyStyles.10.svg
```

**Comment by TrySound** [comment]
Thanks

**Comment by TrySound** [comment]
@XhmikosR Actually bin/svgo is an executable. And now I can't run it directly locally.
```
$ ./bin/svgo input.svg -o output.svg  --pretty
zsh: permission denied: ./bin/svgo
```

**Comment by XhmikosR** [comment]
@TrySound this is just what's tracked in git, not your system? You can make it an executable, but if it should be tracked by git, I don't know. You can revert the bin/svgo change if it works again, although I'm still not sure if it should be tracked by git or not.

**Pull request merged**
