### PR TITLE
README.md: better plugins' sorting

### PR DESCRIPTION
**Pull request by XhmikosR**
Maybe it's my OCD, but I feel like sorting alphabetically is more natural. In the plugins table, I kept the enabled ones at the top.

Let me know what you think :)

### CODE REVIEW

**Comment by TrySound** [comment]
Plugins are specified in order they are run which is critical for optimisation and correctness.

**Comment by XhmikosR** [comment]
Yeah, but in the README, it's harder to find which plugin is enabled if they are sorted randomly...

**Comment by TrySound** [comment]
Copy pasted config will not work so I'd prefer to not confuse anybody.

**Comment by XhmikosR** [comment]
This is more confusing, trying to find a plugin randomly. The CLI help text sorts them by name for example.

Sorting alphabetically is more natural for human beings than random sorting.

**Comment by TrySound** [comment]
@XhmikosR I agree with that. But providing broken config is not human friendly.

**Pull request closed without merging**
