### PR TITLE
Removal of a particular value of an attribute

### PR DESCRIPTION
**Pull request by prashjain309**
Example class="one two"
Calling removeAttr(one) will result in class="two"

### CODE REVIEW

**Comment by prashjain309** [comment]
Hi, awaiting your reply.

**Comment by GreLI** [comment]
Yeah, being rather busy lately. There is a caveat: it applies to any attribute, not just class, which can be confusing if working with spaces.

**Comment by prashjain309** [comment]
So it is generic for all attribute and can be used for any attribute I believe. Should it be restricted to some attributes only?

**Comment by GreLI** [comment]
`class` attributes are `CSSClassList` instances, so it should be handled differently.

**Pull request closed without merging**
