### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Crissov**
reorganize plugins by type
emphasize plugins that are active by default (for `--pretty` I guess)
explain `install -g`

### CODE REVIEW

**Comment by GreLI** [comment]
Closing due to merge conflicts

**Comment by Crissov** [comment]
Could you please elaborate?

**Comment by strarsis** [comment]
@Crissov: Probably because files have changed while this PR hadn't been merged yet.
Now changes by this PR and changes introduced in the meantime are conflicting (cannot be merged automatically).
I guess it would be easier to just re-alphabetize the READMEs and create a new PR that can be just merged in (automatically).

**Comment by Crissov** [comment]
Perhaps, but from the comment I don't get whether this change would be wanted at all, i.e. whether it would be worth my time doing another PR.

**Pull request closed without merging**
