### PR TITLE
add removeXSS plugin

### PR DESCRIPTION
**Pull request by cakeinpanic**
Hi everyone!

I'm using svgo in my project and missing this plugin, so I added it :)
It removes all possible XSS attacks: with event listeners or direct script injection

### CODE REVIEW

**Comment by cakeinpanic** [comment]
fixing https://github.com/svg/svgo/issues/1665

**Comment by nanderv** [comment]
Hi, will this feature still be added?

**Comment by pi0** [comment]
I have directly enabled this plugin in [unjs/ipx](https://ipx.unjs.io) (powring [Nuxt image](https://image.nuxt.com)). 

Thanks for working on this PR @cakeinpanic and wish you best 🤍

**Comment by SethFalco** [comment]
Sorry, you had to wait so long for a review. I'm still triaging the backlog of issues/PRs in the project.

Last month, I updated the `removeScriptElement` plugin to remove all scripts. This will be renamed in v4 to `removeScripts`, and possibly an alias to be added sooner.

As a result, this has already been resolved. Once v3.0.3 is released, one can use `removeScriptElement` to drop `<script>` elements, event attributes, and JavaScript URIs.

Just a heads-up, this PR didn't cover all possible vectors for an XSS attack as it was missing JavaScript URIs, like the following:

```js
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <a href="javascript:(() => { alert('uwu') })();">
    <text y="10">uwu</text>
  </a>
</svg>
```

See: https://github.com/svg/svgo/pull/1807

**Comment by SethFalco** [comment]
@pi0 You may want to review your implementation of `removeXSS` to make sure it handles JavaScript URIs as well until v3.0.3 is released.

Alternatively, you can wait up for the v3.0.3 release, but I can't guarantee a timeline. I've been prodding one of the maintainers to make a release soon as I don't have permissions, but everyone's busy. ^-^'

**Pull request closed without merging**
