### PR TITLE
Avoid encoding script and style elements content

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/svg/svgo/issues/176

@XhmikosR @GreLI

### CODE REVIEW

**Comment by XhmikosR** [comment]
LGTM. Just so that we are safe, do you know what this comment was about? https://github.com/svg/svgo/issues/176#issuecomment-199947766

**Comment by TrySound** [comment]
I actually not sure this is necessary change
https://github.com/svg/svgo/issues/176#issuecomment-913007825

**Review by matheus1lva — APPROVED** [review]

**Comment by GreLI** [comment]
Seems good. But I'm not sure, that things like
```html
<style>
    style::after {
         content: "</style>"
    }
   /* other styles */
</style>
```
will not be broken. Though it's unlikely will be in SVG, and in JS usually there are ways to avoid that (like `'</' + 'script>'`).

**Comment by TrySound** [comment]
Closing until somebody provide a repro with visual regression

**Pull request closed without merging**
