### PR TITLE
Prefix ids plugin don't add prefix if prefix is false

### PR DESCRIPTION
**Pull request by vzaidman**
i use it like this:
```
plugins: [
          {convertPathData: false},
          {prefixIds: {
            prefix: node => {
              const elementName = node && node.elem
              if(!elementName || elementName === 'svg' || elementName === 'use'){
                return false
              }

              return 'some-prefix'
            }
          }}
        ]
```

and i expect no prefix when i return prefix as false.

it can also be used as

```
plugins: [
          {convertPathData: false},
          {prefixIds: {prefix: false}}
        ]
```

### CODE REVIEW

**Comment by strarsis** [comment]
@vzaidman: This is very similar to this issue (please also check out the code sample in that issue):
https://github.com/svg/svgo/issues/913#issuecomment-369423275

**Comment by vzaidman** [comment]
reabsed my fix on develop

**Comment by vzaidman** [comment]
Why don't i see it in thew latest version?
can you please publish it?

**Comment by GreLI** [comment]
SVGO v1.1.0 with the fix has been just released.

**Pull request merged**
