### PR TITLE
Test regressions with W3C SVG 1.1 Test Suite

### PR DESCRIPTION
**Pull request by TrySound**
Visual regressions tests will give us more confidence in SVGO stability.
Test cases are downloaded from w3.org, screenshooted with playwright and
compared with pixelmatch.

See test suite https://www.w3.org/Graphics/SVG/Test/20110816/

Bugs detected with these tests:
- https://github.com/svg/svgo/commit/9b97e06ef69b7961f342c9ee8468c552c9b503a3
- https://github.com/svg/svgo/pull/1371
- https://github.com/svg/svgo/commit/c1d5f0f7a93a6f1c947baa5860ddd40f8d1bb701
- https://github.com/svg/svgo/commit/9de471a0f4bea20581034c2d74b0652c27e0fad0
- https://github.com/svg/svgo/commit/091172a392f6d751855477d51e5c8bd3e44fde97
- https://github.com/svg/svgo/commit/36391564f2d0b2c7ad86c746bacdd6de030ebd3d
- https://github.com/svg/svgo/commit/d14315b68fc1fcb43212219a0da5857ad7a23cd0
- https://github.com/svg/svgo/commit/9d67586787ad16799d7a1cfce1eb0bce829470da
- https://github.com/svg/svgo/commit/d06747abca1e9e652a764db9747395d14f7f6f98
- https://github.com/svg/svgo/commit/dd37fcfebbe2f3cea687ad0bf890ff83ab3c9eb7
- https://github.com/svg/svgo/pull/1378

### CODE REVIEW

**Comment by XhmikosR** [comment]
Shouldn't this run on CI? If so, perhaps a separate job?

**Comment by TrySound** [comment]
Yes, it will be. Not all tests are passing yet. This is why it's draft.

**Comment by sk-** [comment]
Great work @TrySound. I was working on something similar too.

I'm using:

- Data from wiki commons. I have a script to download all the SVG files with a permissible license.
- Rendering from inkscape (This is a bad idea as it has several bugs)
- Image comparison using [reg-cli](https://github.com/reg-viz/reg-cli), which under the hood uses `pixelmatch`, but has a webui which allows to better inspect the differences.
- Issue generator (could be a template as well). See https://github.com/svg/svgo/issues/1362 or https://github.com/svg/svgo/issues/1362 for an idea.

See screenshots attached:

Screen Shot 2021-02-22 at 11 50 00 AM
Screen Shot 2021-02-22 at 11 50 31 AM

Maybe we should create an issue where we can discuss ideas.

**Comment by TrySound** [comment]
Sure, feel free to open one

**Comment by TrySound** [comment]
Current result
Skipped: 97
Mismatched: 0
Passed: 429

**Pull request merged**
