### PR TITLE
add removeScriptElement plugin

### PR DESCRIPTION
**Pull request by pklingem**
addresses https://github.com/svg/svgo/issues/395

### CODE REVIEW

**Comment by GreLI** [comment]
Thanks!

**Comment by pklingem** [comment]
@GreLI any chance you could cut a release for us now that this has been merged?

**Comment by pklingem** [comment]
thanks for the quick response, we'll lock to the sha for the time being.

**Comment by auralon** [comment]
Any ideas when this will get pushed in a release to npm?

**Comment by GreLI** [comment]
As soon as it be ready. Unfortunately, there a lot of things needs to be managed, but things must get easier after that.

**Comment by auralon** [comment]
OK, thanks for the super quick response!  This functionality would be very useful.  It also seems to work OK, from my initial tests.  

Although, at present I am manually setting the `exports.active = false` to `exports.active = true` in the plugin file.  This is the first time I've used `svgo`... how might I otherwise set a plugin to active?

**Comment by pklingem** [comment]
`npm install --save svg/svgo`
`svgo --enable=removeScriptElement -i file -o -`

**Comment by auralon** [comment]
Thanks, @pklingem :)  ...  the version that I'm getting through npm doesn't have the plugin.  I've manually downloaded the plugin and I can get it to work in a node script, but only by manually setting the `exports.active` to true.

That cli command you've given me is useful, but if possible, I'd like to know how it to do the same within a node app.

**Comment by GreLI** [comment]
SVGO v1.0.0 with this plugin has been released now.

**Pull request merged**
