### PR TITLE
Remove unnecessary dependency

### PR DESCRIPTION
**Pull request by Yeti-or**

### CODE REVIEW

**Comment by GreLI** [comment]
Thanks!

**Comment by Yeti-or** [comment]
@caub could you explain where is the typo ?

**Comment by caub** [comment]
https://github.com/svg/svgo/commit/4495a34f55560b2bc05cf837ba9dd01ca20cd479#diff-e2a39016bf512698d27bb1591c306096

**Comment by Yeti-or** [comment]
fixed it here: https://github.com/svg/svgo/pull/687

**Pull request merged**
