### PR TITLE
Fix extra newline at end of -o - output

### PR DESCRIPTION
**Pull request by kriskowal**
Previously, svgo commands using the `-o -` flag to write the output to standard out would end the file with an extra newline. File output does not exhibit this defect. The root cause is using console.log, which adds the newline.

### CODE REVIEW

**Comment by kriskowal** [comment]
@GreLI Please let me know if I can be of any further assistance in bringing this bugfix toward a release.

**Comment by kriskowal** [comment]
cc @deepsweet Please let me know if I can help carry this fix through to a release.

**Comment by kriskowal** [comment]
I no longer need this but still think it’s a good change. Just giving a poke and resigning.

**Comment by kriskowal** [comment]
Hello, @TrySound. I just resolved a lingering conflict in this stale PR. Hope this is helpful.

**Comment by hugolpz** [comment]
@TrySound this seems easy to merge 👯

**Comment by TrySound** [comment]
Thanks!

**Pull request merged**
