### PR TITLE
Bump up js-yaml version to fix DoS vulnerability

### PR DESCRIPTION
**Pull request by eugestarr**
Fixes error described in #1088 
Breaks strict bitbucket pipelines

### CODE REVIEW

**Comment by thomaswangio** [comment]
+1, need this to be fixed for PR to Gatsby https://github.com/gatsbyjs/gatsby/pull/12740

**Comment by muescha** [comment]
Sorry. Wrong repo. But I can not delete my comment

**Comment by charlenetshos** [comment]
Hello, is there any update on this? npm audit is failing in some of our repo because of this vulnerability.

**Comment by thomaswangio** [comment]
@GreLI - can you help merge this? thanks.

**Comment by snailuj** [comment]
We have had to suspend npm audit hooks because of this vulnerability. Obviously not ideal. I know we're all busy, but currently waiting with baited breath for this wee version bump.

**Comment by muescha** [comment]
ping @ deepsweet

**Comment by thomaswangio** [comment]
checking again @deepsweet @GreLI please help us out here

**Comment by etaggus** [comment]
@deepsweet @GreLI will this be merged soon? Our audits have been failing for the past two weeks now.

**Comment by muescha** [comment]
thx :)

**Comment by deepsweet** [comment]
Published as `v1.2.1`

screenshot

Hope that I didn't break anything.

**Pull request merged**
