### PR TITLE
additional option for removeUselessFillStroke, to actually remove inv…

### PR DESCRIPTION
**Pull request by caub**
…isible shapes

Tell me if it makes sense

#638

### CODE REVIEW

**Comment by GreLI** [comment]
It looks like an idea for a separate plugin.

**Comment by GreLI** [comment]
Also better results may be achieved using `computedAttr` which considers inheritance.

**Comment by caub** [comment]
I know, but I use fill and stroke that already use computedAttr, I did it in the same plugin for perf, avoiding to do the same thing (item.computedAttr('stroke'), !item.computedAttr('fill', 'none')) in another plugin

**Comment by caub** [comment]
note: https://github.com/svg/svgo/blob/master/plugins/removeUselessStrokeAndFill.js#L18 is really bad, because this module is required, then this global variable can be changed when running SVGO on one svg, then will keep that value for a next svg

**Comment by caub** [comment]
@GreLI by putting hasStyleOrScript in the config, it allows to make sure a new one is there when running a new instance of SVGO

https://github.com/svg/svgo/pull/655/commits/bcd908691f41b9e300e499d25967d3bb3e2a453f#diff-2b80c20a2dbfb8e48fe3a26d26111ddaR13

it could be possible to make this plugin in full mode, instead of per element, but I think that's fine like that

**Comment by alexjlockwood** [comment]
I think @caub is right that the usage of global variables may be problematic elsewhere as well. For example, in the "removeUselessDefs" plugin, a global 'defs' variable is reassigned various times throughout the plugin's execution. When the plugin exits, the variable will continue to hold a reference to its current value. In this case, I don't think there will be any behavior changes... however, it does seem like at the very least there will be a temporary memory leak (i.e. the referenced element won't be garbage collected until the next time SVGO is run).

Link: https://github.com/svg/svgo/blob/master/plugins/removeUselessDefs.js#L10

**Comment by GreLI** [comment]
In `removeUselessDefs` global variable is used for recursion because of external function. It always will have actual value, so nothing to worry there.

**Pull request merged**
